Update build.yml for Linux and Android configurations

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -36,17 +36,24 @@ jobs:
         with:
           haxe-version: ${{ env.HAXE_VERSION }}
 
+      - name: Update APT
+        if: inputs.name == 'Linux'
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update --fix-missing
+
       - name: Install libVLC
         if: inputs.name == 'Linux'
-        run: sudo apt install libvlc-dev libvlccore-dev
+        run: sudo apt-get install -y libvlc-dev libvlccore-dev
 
       - name: Install Libraries
         run: |
           haxelib install hmm --quiet
           haxelib run hmm install --quiet
 
-      - name: Patch Flixel Android manifest bug
-        if: inputs.name == 'Android'
+      - name: Patch Flixel Android x64 manifest bug
+        if: inputs.name == 'Android x64'
         run: |
           HAXELIB_REPO=$(haxelib config)
           FLIXEL_INCLUDE="$HAXELIB_REPO/flixel/5,6,1/include.xml"
@@ -55,8 +62,26 @@ jobs:
           perl -pi -e 's/ if="\$\{lime &ge; 8\.2\.0\}"//' "$FLIXEL_INCLUDE"
           grep -n "appCategory" "$FLIXEL_INCLUDE"
 
-      - name: Configure Android
-        if: inputs.name == 'Android'
+      - name: Patch Flixel Android x32 manifest bug
+        if: inputs.name == 'Android x32'
+        run: |
+          HAXELIB_REPO=$(haxelib config)
+          FLIXEL_INCLUDE="$HAXELIB_REPO/flixel/5,6,1/include.xml"
+          echo "Patching $FLIXEL_INCLUDE"
+          test -f "$FLIXEL_INCLUDE" || { echo "include.xml not found in $FLIXEL_INCLUDE"; exit 1; }
+          perl -pi -e 's/ if="\$\{lime &ge; 8\.2\.0\}"//' "$FLIXEL_INCLUDE"
+          grep -n "appCategory" "$FLIXEL_INCLUDE"
+
+      - name: Configure Android x64
+        if: inputs.name == 'Android x64'
+        run: |
+          haxelib run lime config ANDROID_SDK $ANDROID_HOME
+          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
+          haxelib run lime config JAVA_HOME $JAVA_HOME_17_arm64
+          haxelib run lime config ANDROID_SETUP true
+
+      - name: Configure Android x32
+        if: inputs.name == 'Android x32'
         run: |
           haxelib run lime config ANDROID_SDK $ANDROID_HOME
           haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
